CC=c:\mingw\bin\gcc

LIBS   = -lgdi32 -lsetupapi

all: prox.exe

prox.exe: prox.c wingui.c command.c
	$(CC) $(CFLAGS) $(DEFINES) -o prox.exe prox.c wingui.c command.c $(LIBS)

clean:
	del prox.exe