#-----------------------------------------------------------------------------
# Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# See LICENSE.txt for the text of the license.
#-----------------------------------------------------------------------------
# Default platform if no platform specified
PLATFORM?=PM3RDV4

# Standalone Mode info (path depends if make is called at top or from armsrc)
# Guard Makefile.hal against implicit rules: (with % to avoid being first goal)
%/Makefile.hal: ;
-include armsrc/Standalone/Makefile.hal
-include Standalone/Makefile.hal
ifndef DEFAULT_STANDALONE
$(error Could not find armsrc/Standalone/Makefile.hal)
endif

define KNOWN_PLATFORM_DEFINITIONS

Known definitions:

+==================================================+
| PLATFORM        | DESCRIPTION              |
+==================================================+
| PM3RDV4 (def)   | Proxmark3 RDV4           |
+--------------------------------------------------+
| PM3GENERIC      | Proxmark3 generic target |
+--------------------------------------------------+
| PM3ICOPYX       | iCopy-X with XC3S100E    |
+--------------------------------------------------+
| PM3ULTIMATE     | Proxmark3 Ultimate with XC2S50 |
+--------------------------------------------------+
| PM5             | Proxmark5 ICEMAN Edition       |
+--------------------------------------------------+

+============================================+
| PLATFORM_EXTRAS | DESCRIPTION              |
+============================================+
| BTADDON         | Proxmark3 RDV4 BT add-on |
+--------------------------------------------+
| BWM             | PM5 Battery Wireless Mod |
+--------------------------------------------+
| NO_LOWBATT_BEEP | PM5 disable low-batt beep|
+--------------------------------------------+
|NO_LOWBATT_SHUTDOWN| PM5 no low-batt cutoff |
+--------------------------------------------+

endef

define HELP_DEFINITIONS

Options to define platform, platform extras and/or standalone mode:

(1) Run make with your PLATFORM, PLATFORM_EXTRAS and/or STANDALONE choices as follows:
make PLATFORM=PM3GENERIC STANDALONE=$(HELP_EXAMPLE_STANDALONE)

(2) Save a file called Makefile.platform with contents, e.g.:
PLATFORM=PM3GENERIC

or if you have a Proxmark 3 RDV4 with the BT add-on:
PLATFORM=PM3RDV4
PLATFORM_EXTRAS=BTADDON

Default standalone mode is $(DEFAULT_STANDALONE).
To disable standalone modes, set explicitly an empty STANDALONE:
STANDALONE=

For Proxmarks with only 256k, you can define
PLATFORM_SIZE=256

to be warned if the image is too big for your device
and you can specify which parts to skip in order to reduce the size:
SKIP_LF=1
SKIP_HITAG=1
SKIP_EM4x50=1
SKIP_EM4x70=1
SKIP_ISO15693=1
SKIP_LEGICRF=1
SKIP_ISO14443b=1
SKIP_ISO14443a=1
SKIP_ICLASS=1
SKIP_FELICA=1
SKIP_NFCBARCODE=1
SKIP_HFSNIFF=1
SKIP_HFPLOT=1
SKIP_ZX8211=1

endef

define KNOWN_DEFINITIONS
$(KNOWN_PLATFORM_DEFINITIONS)
$(KNOWN_STANDALONE_DEFINITIONS)
$(HELP_DEFINITIONS)
endef

PLTNAME = Unknown Platform
PLATFORM_FPGA = fpga-undefined

PLATFORM_DEFS =
ifeq ($(PLATFORM),PM3RDV4)
    # FPGA bitstream files, the order doesn't matter anymore
    FPGA_BITSTREAMS = fpga_pm3_hf.bit
    ifneq ($(SKIP_LF),1)
        FPGA_BITSTREAMS += fpga_pm3_lf.bit
    endif
    ifneq ($(SKIP_FELICA),1)
        FPGA_BITSTREAMS += fpga_pm3_felica.bit
    endif
    ifneq ($(SKIP_ISO15693),1)
        FPGA_BITSTREAMS += fpga_pm3_hf_15.bit
    endif
    PLATFORM_DEFS = -DWITH_SMARTCARD -DWITH_FLASH -DRDV4 -DCHIP_AT91SAM7S
    PLTNAME = Proxmark3 RDV4
    PLATFORM_FPGA = xc2s30
    RDV4 = yes
else ifeq ($(PLATFORM),PM3OTHER)
    $(warning PLATFORM=PM3OTHER is deprecated, please use PLATFORM=PM3GENERIC)
    # FPGA bitstream files, the order doesn't matter anymore
    FPGA_BITSTREAMS = fpga_pm3_hf.bit
    ifneq ($(SKIP_LF),1)
        FPGA_BITSTREAMS += fpga_pm3_lf.bit
    endif
    ifneq ($(SKIP_FELICA),1)
        FPGA_BITSTREAMS += fpga_pm3_felica.bit
    endif
    ifneq ($(SKIP_ISO15693),1)
        FPGA_BITSTREAMS += fpga_pm3_hf_15.bit
    endif
    PLTNAME = Proxmark3 generic target
    PLATFORM_FPGA = xc2s30
    ifeq ($(LED_ORDER),PM3EASY)
        PLATFORM_DEFS = -DLED_ORDER_PM3EASY -DCHIP_AT91SAM7S
    endif
else ifeq ($(PLATFORM),PM3GENERIC)
    # FPGA bitstream files, the order doesn't matter anymore
    FPGA_BITSTREAMS = fpga_pm3_hf.bit
    ifneq ($(SKIP_LF),1)
        FPGA_BITSTREAMS += fpga_pm3_lf.bit
    endif
    ifneq ($(SKIP_FELICA),1)
        FPGA_BITSTREAMS += fpga_pm3_felica.bit
    endif
    ifneq ($(SKIP_ISO15693),1)
        FPGA_BITSTREAMS += fpga_pm3_hf_15.bit
    endif
    PLTNAME = Proxmark3 generic target
    PLATFORM_FPGA = xc2s30
    ifeq ($(LED_ORDER),PM3EASY)
        PLATFORM_DEFS = -DLED_ORDER_PM3EASY -DCHIP_AT91SAM7S
    endif
else ifeq ($(PLATFORM),PM3ICOPYX)
    # FPGA bitstream files, the order doesn't matter anymore - only hf has a bitstream
    FPGA_BITSTREAMS = fpga_icopyx_hf.bit
    PLATFORM_DEFS = -DWITH_FLASH -DICOPYX -DXC3 -DCHIP_AT91SAM7S
    PLTNAME = iCopy-X with XC3S100E
    PLATFORM_FPGA = xc3s100e
else ifeq ($(PLATFORM),PM3ULTIMATE)
    # FPGA bitstream files, the order doesn't matter anymore - only hf has a bitstream
    FPGA_BITSTREAMS = fpga_pm3_ult_hf.bit
    ifneq ($(SKIP_LF),1)
        FPGA_BITSTREAMS += fpga_pm3_ult_lf.bit
    endif
    ifneq ($(SKIP_FELICA),1)
        FPGA_BITSTREAMS += fpga_pm3_ult_felica.bit
    endif
    ifneq ($(SKIP_ISO15693),1)
        FPGA_BITSTREAMS += fpga_pm3_ult_hf_15.bit
    endif
    PLATFORM_DEFS = -DWITH_FLASH -DXC2S50 -DCHIP_AT91SAM7S
    PLTNAME = Proxmark3 Ultimate with XC2S50
    PLATFORM_FPGA = xc2s50
else ifeq ($(PLATFORM),PM5)
    # TODO DXL 我们暂时不需要指定FPGA比特流文件，因为实际上我们大概率要做FPGA的静态烧录，而不是附加到ARM固件中动态下载
    FPGA_BITSTREAMS = fpga_pm3_hf.bit # TODO DXL 虽然可以不把打包比特流，但是还是得把FPGA的版本信息给生成，让EXE依赖。
    SKIP_FPGA_EMBED = true # important!!! disable the fpga bit files pack to arm!
    SKIP_COMPRESSION = true # Skip data section compress. The new mcu has enough flash space.
    PLATFORM_DEFS = -DWITH_FLASH -DPM5 -DCHIP_AT32F435_37 -DWITH_BWM_STATUS -DWITH_PM5_PWR_LED -DWITH_PM5_AUTOOFF -DWITH_BWM_LOWBATT_BEEP -DWITH_PM5_LOWBATT_SHUTDOWN # TODO 暂时不要编译i2c -DWITH_SMARTCARD
                    # Low-battery safety (beep + over-discharge power-off at ~3.3V) is ON by default.
                    # Opt out via PLATFORM_EXTRAS:
                    #   NO_LOWBATT_SHUTDOWN  ===== keep the beep, disable auto power-off ====
                    #   NO_LOWBATT_BEEP      ===== disable the beep (also drops the shutdown poll) ====
    PLTNAME = Proxmark5
    PLATFORM_FPGA = GW1NR-LV2MG49GC6/i5
else
    $(error Invalid or empty PLATFORM: $(PLATFORM). $(KNOWN_DEFINITIONS))
endif

# parsing additional PLATFORM_EXTRAS tokens
PLATFORM_EXTRAS_TMP:=$(PLATFORM_EXTRAS)
ifneq (,$(findstring SMARTCARD,$(PLATFORM_EXTRAS_TMP)))
    PLATFORM_DEFS += -DWITH_SMARTCARD
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out SMARTCARD,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(findstring FLASH,$(PLATFORM_EXTRAS_TMP)))
    PLATFORM_DEFS += -DWITH_FLASH
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out FLASH,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(findstring BTADDON,$(PLATFORM_EXTRAS_TMP)))
    ifeq ($(PLATFORM),PM5)
        $(error Incompatible PLATFORM_EXTRAS token BTADDON)
    endif
    PLATFORM_DEFS += -DWITH_FPC_USART_HOST
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out BTADDON,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(findstring FPC_USART_DEV,$(PLATFORM_EXTRAS_TMP)))
    ifeq ($(PLATFORM),PM5)
        $(error Incompatible PLATFORM_EXTRAS token FPC_USART_DEV)
    endif
    PLATFORM_DEFS += -DWITH_FPC_USART_DEV
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out FPC_USART_DEV,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(findstring BWM,$(PLATFORM_EXTRAS_TMP)))
    ifneq ($(PLATFORM),PM5)
        $(error PLATFORM_EXTRAS token BWM is only valid on PLATFORM=PM5)
    endif
    PLATFORM_DEFS += -DWITH_BWM_FORWARD
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out BWM,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(findstring NO_LOWBATT_SHUTDOWN,$(PLATFORM_EXTRAS_TMP)))
    ifneq ($(PLATFORM),PM5)
        $(error PLATFORM_EXTRAS token NO_LOWBATT_SHUTDOWN is only valid on PLATFORM=PM5)
    endif
    PLATFORM_DEFS := $(filter-out -DWITH_PM5_LOWBATT_SHUTDOWN,$(PLATFORM_DEFS))
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out NO_LOWBATT_SHUTDOWN,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(findstring NO_LOWBATT_BEEP,$(PLATFORM_EXTRAS_TMP)))
    ifneq ($(PLATFORM),PM5)
        $(error PLATFORM_EXTRAS token NO_LOWBATT_BEEP is only valid on PLATFORM=PM5)
    endif
    # beep is the carrier for the shutdown poll, so dropping it drops shutdown too
    PLATFORM_DEFS := $(filter-out -DWITH_BWM_LOWBATT_BEEP -DWITH_PM5_LOWBATT_SHUTDOWN,$(PLATFORM_DEFS))
    PLATFORM_EXTRAS_TMP := $(strip $(filter-out NO_LOWBATT_BEEP,$(PLATFORM_EXTRAS_TMP)))
endif
ifneq (,$(PLATFORM_EXTRAS_TMP))
    $(error Unknown PLATFORM_EXTRAS token(s): $(PLATFORM_EXTRAS_TMP))
endif

# common LF support
ifneq ($(SKIP_LF),1)
    PLATFORM_DEFS += -DWITH_LF
endif
ifneq ($(SKIP_HITAG),1)
    PLATFORM_DEFS += -DWITH_HITAG
endif
ifneq ($(SKIP_EM4x50),1)
    PLATFORM_DEFS += -DWITH_EM4x50
endif
ifneq ($(SKIP_EM4x70),1)
    PLATFORM_DEFS += -DWITH_EM4x70
endif
ifneq ($(SKIP_ZX8211),1)
    PLATFORM_DEFS += -DWITH_ZX8211
endif

# common HF support
ifneq ($(SKIP_HF),1)
    PLATFORM_DEFS += -DWITH_GENERAL_HF
endif
ifneq ($(SKIP_ISO15693),1)
    PLATFORM_DEFS += -DWITH_ISO15693
endif
ifneq ($(SKIP_LEGICRF),1)
    PLATFORM_DEFS += -DWITH_LEGICRF
endif
ifneq ($(SKIP_ISO14443b),1)
    PLATFORM_DEFS += -DWITH_ISO14443b
endif
ifneq ($(SKIP_ISO14443a),1)
    PLATFORM_DEFS += -DWITH_ISO14443a
endif
ifneq ($(SKIP_ICLASS),1)
    PLATFORM_DEFS += -DWITH_ICLASS
endif
ifneq ($(SKIP_SEOS),1)
    PLATFORM_DEFS += -DWITH_SEOS
endif
ifneq ($(SKIP_FELICA),1)
    PLATFORM_DEFS += -DWITH_FELICA
endif
ifneq ($(SKIP_NFCBARCODE),1)
    PLATFORM_DEFS += -DWITH_NFCBARCODE
endif
ifneq ($(SKIP_HFSNIFF),1)
    PLATFORM_DEFS += -DWITH_HFSNIFF
endif
ifneq ($(SKIP_HFPLOT),1)
    PLATFORM_DEFS += -DWITH_HFPLOT
endif
ifneq ($(SKIP_COMPRESSION),1)
    PLATFORM_DEFS += -DWITH_COMPRESSION
endif

# Standalone mode
ifneq ($(strip $(filter $(PLATFORM_DEFS),$(STANDALONE_REQ_DEFS))),$(strip $(STANDALONE_REQ_DEFS)))
    $(error Chosen Standalone mode $(STANDALONE) requires $(strip $(STANDALONE_REQ_DEFS)), unsupported by $(PLTNAME))
endif
ifneq (,$(STANDALONE_PLATFORM_DEFS))
    PLATFORM_DEFS+=$(STANDALONE_PLATFORM_DEFS)
endif

$(info $(findstring WITH_STANDALONE_*,$(PLATFORM_DEFS)))

# Misc (LCD support)
ifneq (,$(findstring WITH_LCD,$(PLATFORM_DEFS)))
    #PLATFORM_DEFS += -DWITH_LCD
endif

# Add flags dependencies :

# WITH_FPC_USART_* needs WITH_FPC_USART :
ifneq (,$(findstring WITH_FPC_USART_,$(PLATFORM_DEFS)))
    PLATFORM_DEFS += -DWITH_FPC_USART
    ifeq ($(USART_BAUD_RATE),)
        USART_BAUD_RATE=115200
    endif
    PLATFORM_DEFS += -DUSART_BAUD_RATE=$(USART_BAUD_RATE)
endif

PLATFORM_DEFS_INFO = $(strip $(filter-out STANDALONE%, $(subst -DWITH_,,$(PLATFORM_DEFS))))
PLATFORM_DEFS_INFO_STANDALONE = $(strip $(subst STANDALONE_,, $(filter STANDALONE%, $(subst -DWITH_,,$(PLATFORM_DEFS)))))

# Check that only one Standalone mode has been chosen
ifneq (,$(word 2, $(PLATFORM_DEFS_INFO_STANDALONE)))
    $(error You must choose only one Standalone mode!: $(PLATFORM_DEFS_INFO_STANDALONE))
endif

PLATFORM_EXTRAS_INFO = $(PLATFORM_EXTRAS)
# info when no extra
ifeq (,$(PLATFORM_EXTRAS_INFO))
    PLATFORM_EXTRAS_INFO = No extra selected
endif

# info when no standalone mode
ifeq (,$(PLATFORM_DEFS_INFO_STANDALONE))
    PLATFORM_DEFS_INFO_STANDALONE = No standalone mode selected
endif

ifeq ($(PLATFORM_SIZE),)
    PLATFORM_SIZE=512
endif

PLATFORM_CHANGED=false
ifneq ($(PLATFORM), $(CACHED_PLATFORM))
    PLATFORM_CHANGED=true
else ifneq ($(PLATFORM_EXTRAS), $(CACHED_PLATFORM_EXTRAS))
    PLATFORM_CHANGED=true
else ifneq ($(strip $(PLATFORM_DEFS)), $(strip $(CACHED_PLATFORM_DEFS)))
    PLATFORM_CHANGED=true
endif

export PLATFORM
export PLATFORM_EXTRAS
export PLATFORM_EXTRAS_INFO
export PLATFORM_SIZE
export PLTNAME
export PLATFORM_FPGA
export PLATFORM_DEFS
export PLATFORM_DEFS_INFO
export PLATFORM_DEFS_INFO_STANDALONE
export PLATFORM_CHANGED
export FPGA_BITSTREAMS

$(info ===================================================================)
$(info Version info:      $(shell tools/mkversion.sh --short 2>/dev/null || ../tools/mkversion.sh --short 2>/dev/null))
$(info Platform name:     $(PLTNAME))
$(info PLATFORM:          $(PLATFORM))
$(info PLATFORM_FPGA:     $(PLATFORM_FPGA))
$(info PLATFORM_SIZE:     $(PLATFORM_SIZE))
$(info Platform extras:   $(PLATFORM_EXTRAS_INFO))
$(info Included options:  $(PLATFORM_DEFS_INFO))
$(info Standalone mode:   $(PLATFORM_DEFS_INFO_STANDALONE))
$(info ===================================================================)
