MYSRCPATHS =
MYINCLUDES = -I. -I..
MYCFLAGS = -std=c99 -D_ISOC99_SOURCE
MYDEFS =
MYSRCS = \
	aes.c \
	asn1parse.c \
	asn1write.c \
	base64.c \
	bignum.c \
	ctr_drbg.c \
	entropy_poll.c \
	entropy.c \
	error.c \
	timing.c \
	ecp.c \
	ecp_curves.c \
	certs.c \
	camellia.c \
	blowfish.c \
	cipher_wrap.c \
	cipher.c \
	cmac.c \
	des.c \
	ecdsa.c \
	md.c \
	md_wrap.c \
	md5.c \
	oid.c \
	pem.c \
	arc4.c \
	pk.c \
	pk_wrap.c \
	pkwrite.c \
	pkcs5.c \
	pkcs12.c \
	pkparse.c \
	platform.c \
	platform_util.c \
	rsa.c \
	rsa_internal.c \
	sha1.c \
	sha256.c \
	sha512.c \
	threading.c \
	x509.c \
	x509_crl.c \
	x509_crt.c

LIB_A = libmbedtls.a

include ../../Makefile.host
