local _names = {
    --[[
    --]]
	["0000"]="WHIRLWIND",
	["0100"]="SONIC BOOM",
	["0200"]="WARNADO",
	["0300"]="LIGHTNINGROD",
	["0400"]="BASH",
	["0500"]="TERRAFIN",
	["0600"]="DINORANG" ,
	["0700"]="LIGHTCORE PRISM BREAK",
	["0800"]="SUNBURN",
	["0900"]="LIGHTCORE ERUPTOR",
	["0A00"]="IGNITOR",
	["0B00"]="FLAMESLINGER",
	["0C00"]="ZAP",
	["0D00"]="WHAM SHELL",
	["0E00"]="GILL GRUNT",
	["0F00"]="SLAMBAM",
	["1000"]="SPYRO",
	["1100"]="VOODOOD",
	["1200"]="DOUBLE TROUBLE",
	["1300"]="TRIGGER HAPPY",
	["1400"]="DROBOT",
	["1500"]="DRILLSERGEANT",
	["1600"]="BOOMER",
	["1700"]="WRECKING BALL",
	["1800"]="CAMO",
	["1900"]="ZOOK",
	["1A00"]="STEALTH ELF",
	["1B00"]="STUMP SMASH",
	["1D00"]="HEX",
	["1C00"]="DARK SPYRO",
	["1E00"]="CHOPCHOP",
	["1F00"]="GHOST ROASTER",
	["2000"]="CYNDER",	
	--[[
	GIANTS
    --]]
	["6400"]="GIANT JET-VAC",
	["6500"]="GIANT SWARM",
	["6600"]="GIANT CRUSHER",
	["6700"]="GIANT FLASHWING",
	["6800"]="GIANT HOTHEAD",
	["6900"]="GIANT HOTDOG",
	["6A00"]="GIANT CHILL",
	["6B00"]="GIANT THUMPBACK",
	["6C00"]="GIANT POPFIZZ",
	["6D00"]="GIANT NINJINI",
	["6E00"]="GIANT BOUNCER",
	["6F00"]="GIANT SPROCKET",
	["7000"]="GIANT TREE REX",
	["7100"]="LIGHTCORE SHROOMBOOM",
	["7200"]="GIANT EYEBROAWL",
	["7300"]="GIANT FRIGHTRIDER",

    --[[
	ITEM
    --]]	
	["C800"]="ANVIL",
	["C900"]="SECRET STASH",
	["CA00"]="REGENERATION",
	["CD00"]="SHIELD",
	["CB00"]="CROSSED SWORDS",
	["CC00"]="HOURGLASS",
	["CE00"]="SPEED BOOTS",
	["CF00"]="SPARX",
	["D000"]="CANNON",
	["D100"]="SCORPIONSTRIKER",

	--[[
	ITEM TRAPS
    --]]
	["D200"]="MAGIC TRAP",
	["D300"]="WATER TRAP",
	["D400"]="AIR TRAP",
	["D500"]="UNDEAD TRAP",
	["D600"]="TECH TRAP",
	["D700"]="FIRE TRAP",
	["D800"]="EARTH TRAP",
	["D900"]="LIFE TRAP",
	["DA00"]="DARK TRAP",
	["DB00"]="LIGHT TRAP",
	["DC00"]="KAOS TRAP",	

    --[[
	ITEM 
    --]]	
	["E600"]="HAND OF FATE",	
	["E700"]="PIGGYBANK",	
	["E800"]="ROCKET RAM",	
	["E900"]="TIKI SPEAKY",	


    --[[
	EXPANSION
    --]]
	["2C01"]="DRAGONS PEAK",
	["2D01"]="EMPIRE OF ICE",
	["2E01"]="PIRATE SEAS",
	["2F01"]="DARKLIGHT CRYPT",
	["3001"]="VOLCANIC VAULT",
	["3101"]="MIRROR OF MYSTERY",
	["3201"]="NIGHTMARE EXPRESS",
	["3301"]="SUNSCRAPER SPIRE",
	["3401"]="MIDNIGHT MUSEUM",
	
	--[[
	LEGENDARY
    --]]	
	["9401"]="LEGENDARY BASH",
	["A001"]="LEGENDARY SPYRO",
	["A301"]="LEGENDARY TRIGGER HAPPY",
	["AE01"]="LEGENDARY CHOPCHOP",
	--legendary blades
	--legendary bouncer
	--legendary zoo lou
	--legendary stealth elf
	--legendary slam bam
	--legendary night shift
	--legendary jet-vac
	--legendary ignitor
	--legendary jawbreaker
	--legendary lightcore grim creeper
	--legendary lightcore chill
	--legendary free ranger
	
	--[[
	COLOR
	--]]
	
	--[[
	TRAPTEAM
    --]]
	["C201"]="TRAPTEAM GUSTO",
	["C301"]="TRAPTEAM THUNDERBOLT",
	["C401"]="TRAPTEAM FLING KONG",
	["C501"]="TRAPTEAM BLADES",
	["C601"]="TRAPTEAM WALLOP",
	["C701"]="TRAPTEAM HEAD RUSH",
	["C801"]="TRAPTEAM FIST BUMP",
	["C901"]="TRAPTEAM ROCKY ROLL",
	["CA01"]="TRAPTEAM WILDFIRE",
	["CB01"]="TRAPTEAM KA BOOM",
	["CC01"]="TRAPTEAM TRAIL BLAZER",
	["CD01"]="TRAPTEAM TORCH",
	["CE01"]="TRAPTEAM SNAP SHOT",
	["CF01"]="TRAPTEAM LOB STAR",
	["D001"]="TRAPTEAM FLIP WRECK",
	["D101"]="TRAPTEAM ECHO",
	["D201"]="TRAPTEAM BLASTERMIND",
	["D301"]="TRAPTEAM ENIGMA",
	["D401"]="TRAPTEAM DEJA VU",
	["D501"]="TRAPTEAM COBRA CADABRA",
	["D601"]="TRAPTEAM JAWBREAKER",	
	["D701"]="TRAPTEAM GEARSHIFT",
	["D801"]="TRAPTEAM CHOPPER",
	["D901"]="TRAPTEAM TREAD HEAD",
	["DA01"]="TRAPTEAM BUSHWHACK",
	["DB01"]="TRAPTEAM TUFF LUCK",
	["DC01"]="TRAPTEAM FOOD FIGHT",
	["DD01"]="TRAPTEAM HIGH FIVE",
	["DE01"]="TRAPTEAM NITRO KRYPT KING",
	["DF01"]="TRAPTEAM SHORT CUT",
	["E001"]="TRAPTEAM BAT SPIN",
	["E101"]="TRAPTEAM FUNNY BONE",
	["E201"]="TRAPTEAM KNIGHT LIGHT",
	["E301"]="TRAPTEAM SPOTLIGHT",
	["E401"]="TRAPTEAM KNIGHT MARE",
	["E501"]="TRAPTEAM BLACKOUT",

	--[[
	PET / MINI
	--]]
	["F601"]="PET BOP",
	["F701"]="PET SPRY",
	["F801"]="PET HIJINX",
	["F901"]="PET TERRAFIN",
	["FA01"]="PET BREEZE",
	["FB01"]="PET WEERUPTOR",
	["FC01"]="PET PET VAC",
	["FD01"]="PET SMALL FRY",
	["FE01"]="PET DROBIT",
	["0202"]="PET GILL GRUNT",
	["0702"]="PET TRIGGER SNAPPY",
	["0E02"]="PET WHISPER ELF",
	["1C02"]="PET BARKLEY",
	["1D02"]="PET THUMPLING",
	["1E02"]="PET MINI JINI",
	["1F02"]="PET EYE SMALL",

	--[[
	SWAP FORCE
	--]]
	["B80B"]="SWAPFORCE SCRATCH",
	["B90B"]="SWAPFORCE POPTHORN",
	["BA0B"]="SWAPFORCE SLOBBER TOOTH",
	["BB0B"]="SWAPFORCE SCORP",
	["BC0B"]="SWAPFORCE HOG WILD FRYNO",
	["BD0B"]="SWAPFORCE SMOLDER DASH",
	["BE0B"]="SWAPFORCE BUMBLE BLAST",
	["BF0B"]="SWAPFORCE ZOO LOU",
	["C00B"]="SWAPFORCE DUNE BUG",
	["C10B"]="SWAPFORCE STAR STRIKE",
	["C20B"]="SWAPFORCE COUNTDOWN",
	["C30B"]="SWAPFORCE WIND UP",
	["C40B"]="SWAPFORCE ROLLER BRAWL",
	["C50B"]="SWAPFORCE GRIM CREEPER",
	["C60B"]="SWAPFORCE RIP TIDE",
	["C70B"]="SWAPFORCE PUNK SHOCK",
}
return _names
