get_craptev1:
	wget -N http://crapto1.netgarage.org/craptev1-v1.1.tar.xz
	tar Jxvf craptev1-v1.1.tar.xz -C craptev1-v1.1

get_crapto1:
	wget -N http://crapto1.netgarage.org/crapto1-v3.3.tar.xz
	tar Jxvf crapto1-v3.3.tar.xz -C crapto1-v3.3

get_nonce_bf:
#	git clone https://github.com/J-Run/mf_key_brute.git mf_key_brute
	git clone https://github.com/iceman1001/mf_nonce_brute mf_nonce_brute	