name: GUI CI

on:
  push:
    paths:
      - 'gui/**'
  pull_request:
    paths:
      - 'gui/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e gui
          pip install pytest build
      - name: Run tests
        run: |
          pytest -q gui/tests

      - name: Build wheel
        run: |
          python -m build -w gui -o dist_gui

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pm3-gui-wheel
          path: dist_gui/*.whl
